[package]
name = "bioleptic-python"
version = "0.1.0"
edition = "2024"

[dependencies]
bioleptic = { path = "../" }
pyo3 = { version = "0.28.2", features = ["extension-module"] }
numpy = "0.28.0"

[profile.release]
lto = true
codegen-units = 1